### ISSUE TITLE
Can run test_reassembly.py

### ISSUE THREAD

**Issue by jonathan-dev** [JarryShaw/PyPCAPKit#100]
I am trying to run test_reassembly.py and get the folloing error:

**System information**
A clear and concise description of your system information.
 - OS Version: manjaro
 - Python Version: 3.10.2
 - Python Implementation: CPython

```Traceback (most recent call last):
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 531, in record_frames
    self._read_frame()
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 874, in _read_frame
    return self._default_read_frame()
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 902, in _default_read_frame
    frame = Frame(self._ifile, num=self._frnum+1, proto=self._dlink,
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/protocols/protocol.py", line 307, in __init__
    self.__post_init__(file, length, **kwargs)  # type: ignore[arg-type]
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/protocols/misc/pcap/frame.py", line 279, in __post_init__
    self._prot = header.network
AttributeError: 'Header' object has no attribute 'network'
```

**Comment by jonathan-dev** [comment]
just forgot to `pip install dpkt `
