### ISSUE TITLE
Error running test_reassembly.py

### ISSUE THREAD

**Issue by jonathan-dev** [JarryShaw/PyPCAPKit#101]
running the test_reassembly.py test fails seemingly independently of the used PCAP file.

**System information**
A clear and concise description of your system information.
 - OS Version: manjaro
 - Python Version: 3.10.2
 - Python Implementation: CPython

```
Traceback (most recent call last):
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 531, in record_frames
    self._read_frame()
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 871, in _read_frame
    return self._dpkt_read_frame()
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/foundation/extraction.py", line 1167, in _dpkt_read_frame
    flag, data = tcp_reassembly(packet, count=self._frnum)
  File "/home/jo/Desktop/tmp/PyPCAPKit/pcapkit/toolkit/dpkt.py", line 204, in tcp_reassembly
    ip = packet['ip']
  File "/home/jo/Desktop/tmp/PyPCAPKit/.env/lib/python3.10/site-packages/dpkt/dpkt.py", line 188, in __getitem__
    raise KeyError(kls)
KeyError: 'ip'
```

**Expected behavior**
run without error

As far as I have investigated this comparison `if dd.__class__ == kls:` causes the problem because it fails to identify the ip class.

maybe the DPKT has change the API and caused the test to fail.

I doesn't crash if the engine is changed to SCAPY

**Comment by JarryShaw** [comment]
Fixed in version `0.16.0`. Package will be synced on PyPI distributioin ASAP.
